### PR TITLE
KOGITO-5601 : Add KogitoInfra capablities in RHPAM Kogito Operator

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
Many thanks for submitting your Pull Request :heart:! 

https://issues.redhat.com/browse/KOGITO-5601

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Please just take a look in the OLM error.

**Comment by vaibhavjainwiz** [comment]
> Please just take a look at the OLM error.

I had raised OLM fix with https://github.com/kiegroup/kogito-operator/pull/927/commits/ec7a89ffc2aa1b91c0d12361c95521cc95a46f6d

**Comment by spolti** [comment]
> > Please just take a look at the OLM error.
> 
> I had raised OLM fix with [ec7a89f](https://github.com/kiegroup/kogito-operator/commit/ec7a89ffc2aa1b91c0d12361c95521cc95a46f6d)

@vaibhavjainwiz the commit you mentioned comes from? didn't find a PR or the commit on main branch.

**Comment by vaibhavjainwiz** [comment]
> > > Please just take a look at the OLM error.
> > 
> > 
> > I had raised OLM fix with [ec7a89f](https://github.com/kiegroup/kogito-operator/commit/ec7a89ffc2aa1b91c0d12361c95521cc95a46f6d)
> 
> @vaibhavjainwiz the commit you mentioned comes from? didn't find a PR or the commit on main branch.

I added this commit as a part of my existing PR of KOGITO-4470
https://github.com/kiegroup/kogito-operator/pull/927

**Comment by spolti** [comment]
@vaibhavjainwiz ok, thanks.

**Review by sutaakar — APPROVED** [review]
Looks good to me.

**Comment by spolti** [comment]
The PR that contains the OLM fix is merged, probably needs  rebase.

**Review by spolti — APPROVED** [review]

**Pull request merged**
