### PR TITLE
[KOGITO-4675] Kogito operator PR check doesn't work after repository …

### PR DESCRIPTION
**Pull request by sutaakar**
…rename

https://issues.redhat.com/browse/KOGITO-4675

Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
deploy and promote pipelines would also need to be modified (env `REPO_NAME`):
- https://github.com/kiegroup/kogito-operator/blob/master/.jenkins/dsl/jobs.groovy#L123
- https://github.com/kiegroup/kogito-operator/blob/master/.jenkins/dsl/jobs.groovy#L181

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
bats test stuck but unrelated here. merging

**Review by Kaitou786 — APPROVED** [review]
lgtm. 
Do we have any jira to change the go module name from `github.com/kiegroup/kogito-cloud-operator` to `github.com/kiegroup/kogito-operator` we would also need to make changes in the CSV with the repo name. I am not sure but will it be something that @vaibhavjainwiz you'll do in the productization effort?

**Comment by vaibhavjainwiz** [comment]
> lgtm.
> Do we have any jira to change the go module name from `github.com/kiegroup/kogito-cloud-operator` to `github.com/kiegroup/kogito-operator` we would also need to make changes in the CSV with the repo name. I am not sure but will it be something that @vaibhavjainwiz you'll do in the productization effort?

@Kaitou786 I had create below Jira to change repo in all required places. Currently I had mentioned kie-docs, Jenkin pipeline and csv need to be changes for it. Please add more point if you found.
https://issues.redhat.com/browse/KOGITO-4678

**Pull request merged**
