### PR TITLE
[KOGITO-4605] Setup BDD test for Product kogito operator

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-4605

Related PR - https://github.com/kiegroup/rhpam-kogito-operator/pull/3

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by sutaakar** [comment]
`bdd_executor.go ` is a 99% of main_test.go (with added lifecycle hooks)
The reason to move the code it to be able to share it, functions defined in test files cannot be called from outside.

**Comment by ricardozanini** [comment]
> `bdd_executor.go ` is a 99% of main_test.go (with added lifecycle hooks)
> The reason to move the code it to be able to share it, functions defined in test files cannot be called from outside.

I think having a shared `bdd` module on upstream, won't be too harmful if it helps us sharing functionality.

**Comment by sutaakar** [comment]
>      I think having a shared bdd module on upstream, won't be too harmful if it helps us sharing functionality.

Yes, that would be a good idea, to mode common code there and keep just specific functionality in test folder. Though that would require a complex rewrite, currently there is a need for relatively quick solution. Will think about it ....

**Review by ricardozanini — APPROVED** [review]
Changes from the API point of view seem fine to me. Many thanks!

**Review by radtriste — COMMENTED** [review]
Good with the changes.

For the `@rhpam` tag, do we want to test native ? Thought it would be supported later

**Comment by sutaakar** [comment]
@radtriste Not sure how is it with native support.

**Comment by sutaakar** [comment]
@radtriste Tags updated, native is no longer tested for RHPAM.

**Review by radtriste — APPROVED** [review]

**Comment by sutaakar** [comment]
Adjusted mappers to be possible to reuse them for product.

**Review by radtriste — APPROVED** [review]

**Comment by sutaakar** [comment]
`@rhpam` annotation added for example images

**Review by radtriste — APPROVED** [review]

**Pull request merged**
