### PR TITLE
[KOGITO-6293] Update metric endpoint in kogito-operator

### PR DESCRIPTION
**Pull request by amygaoo**
See: https://issues.redhat.com/browse/KOGITO-6293

## Changes
Added monitoring constants for quarkus and springboot and removed previous `/metrics` endpoint.

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

### CODE REVIEW

**Review by spolti — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by vaibhavjainwiz — APPROVED** [review]

**Comment by radtriste** [comment]
we should launch the BDD tests 24 hours after https://github.com/kiegroup/kogito-examples/pull/990 is merged

**Review by sutaakar — APPROVED** [review]
Code looks ok.
BDD tests need to be updated and the PR tested once runtime PR is merged.

**Comment by radtriste** [comment]
@amygaoo added a commit to correct the CLI build error

@ricardozanini This bug about the CLI construction, I think we may need to update the `make before-pr` command so it also builds the CLI as part of it, so it updates the `go.sum`. This would avoid the kind of problems we are just having. wdyt ?

**Comment by radtriste** [comment]
Dependent PRs have been merged (although it seems it was not so dependent)
so this one can be merged once green on BDD tests

**Comment by gitgabrio** [comment]
@radtriste @vaibhavjainwiz 
IIUC,  https://github.com/kiegroup/kogito-runtimes/pull/1735 should have been merged after this PR, since this PR remove usage of "/metrics" endpoint, and the other one (merged) actually remove them: am I wrong ?

**Comment by radtriste** [comment]
retrying for failing tests:
- Install Kogito Data Index with Infinispan
- Deploy dmn-drools-quarkus-metrics service and verify that it successfully connects to Prometheus

/jenkins test

**Comment by radtriste** [comment]
retrying for failing tests:

- Install Kogito Data Index with Infinispan

/jenkins test

**Pull request merged**
