### PR TITLE
KOGITO-5685 RHPAM BDD tests with events

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-5685

Related PRs:
- https://github.com/kiegroup/kogito-operator/pull/968
- https://github.com/kiegroup/rhpam-kogito-operator/pull/63

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
Need first https://github.com/kiegroup/kogito-operator/pull/966 to be merged

**Review by sutaakar — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
@sutaakar the issue you fixed on the other PR about the headers, is related with the failure here?

**Comment by sutaakar** [comment]
@spolti Yes, it is related.

**Comment by radtriste** [comment]
BDD tests failure is Grafana one (known issue)

**Pull request merged**
