### PR TITLE
[KOGITO-5256] - Fix Knative Trigger creation

### PR DESCRIPTION
**Pull request by ricardozanini**
Many thanks for submitting your Pull Request :heart:! 

See: https://issues.redhat.com/browse/KOGITO-5256

The creation of Knative Triggers was incorrect. The filter must rely on CE Type instead of Kogito Topic name.

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by ricardozanini** [comment]
@sutaakar, if you would check this PR, could you please make available the operator image for @mouachan to test it in his environment if you check this PR? Many thanks!!

/jenkins test

**Review by vaibhavjainwiz — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]
Looks good to me, works as expected.
Built image is available on `quay.io/ksuta/kogito-operator:5256`

**Comment by sutaakar** [comment]
Test failure unrelated, reported as https://issues.redhat.com/browse/KOGITO-5262

**Comment by ricardozanini** [comment]
Many thanks, @sutaakar! @mouachan  were you able to test it?

**Comment by ricardozanini** [comment]
Tested by QE and community user, merging!

**Pull request merged**
