### PR TITLE
[1.5.x][KOGITO-4952] Support installing product operator using insecure regi…

### PR DESCRIPTION
**Pull request by sutaakar**
…stry

https://issues.redhat.com/browse/KOGITO-4952

Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
looks like https://nexus-kogito-tools.apps.kogito-cloud.automation.rhmw.io/repository/maven-public/ is not accessible ...

**Comment by msmagnanijr** [comment]
> looks like https://nexus-kogito-tools.apps.kogito-cloud.automation.rhmw.io/repository/maven-public/ is not accessible ...
> @msmagnanijr
I'm sorry guys. The nexus isn't really there because I didn't sync with the ArgoCD last Friday. I'm going to do that now and I will let you know.

**Comment by msmagnanijr** [comment]
> > looks like https://nexus-kogito-tools.apps.kogito-cloud.automation.rhmw.io/repository/maven-public/ is not accessible ...
> > @msmagnanijr
> 
> I'm sorry guys. The nexus isn't really there because I didn't sync with the ArgoCD last Friday. I'm going to do that now and I will let you know.

Done!

**Pull request merged**
