### PR TITLE
BXMSPROD-1478 Setup Jenkins pipelines with new golang

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/BXMSPROD-1478

Depends on
- https://github.com/kiegroup/kogito-pipelines/pull/263
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1107

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by radtriste** [comment]
Failing tests due to https://issues.redhat.com/browse/KOGITO-5977

**Comment by radtriste** [comment]
PR is ok on IBMCloud. Once merged, will deactivate the hook from AWS.

**Review by sutaakar — APPROVED** [review]

**Pull request merged**
