### PR TITLE
[1.11.x] [KOGITO-5977] Pod is never created when deploying source…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
… files

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by spolti** [comment]
cherry-picked https://github.com/kiegroup/kogito-operator/pull/1037

**Review by spolti — APPROVED** [review]

**Comment by vaibhavjainwiz** [comment]
BDD test are failing with below error:
```
Transfer failed for https://nexus-kogito-tools.apps.kogito.automation.rhmw.io/repository/maven-public/org/kie/kogito/kogito-build-parent/1.11.2-SNAPSHOT/maven-metadata.xml
```

**Review by radtriste — APPROVED** [review]

**Pull request merged**
