### PR TITLE
KOGITO-5262 Remove reference to no longer used consumers

### PR DESCRIPTION
**Pull request by cristianonicolai**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
Jenkins seems to have some problems: `java.io.IOException: No space left on device`
I pinged @msmagnanijr to have a look

**Review by radtriste — APPROVED** [review]
as long as test are passing, I am good with that change

**Review by ricardozanini — APPROVED** [review]

**Comment by sutaakar** [comment]
The latest nightly Data index image contains **old** Data index application which doesn't contain changes done in https://github.com/kiegroup/kogito-apps/pull/844. As a result the Data index still expects removed topics in its `microprofile-config.properties`, failing to start properly. This needs to be addressed to be able to run the BDD tests properly.

**Comment by cristianonicolai** [comment]
@sutaakar anything I can help with to get the data index nightly correctly published?

**Comment by sutaakar** [comment]
@cristianonicolai no, Tristan is looking on pipeline adjustments to partly avoid the problem, should be (hopefully) working once the error in Kogito apps is addressed.

**Comment by radtriste** [comment]
@cristianonicolai @sutaakar If the whole `kogito-apps` does not pass tests, then we do not upload artifacts to Nexus. Maybe we should think about building the successful apps and pushing them to repo even if others have problems. But that could be tricky ...

**Review by spolti — APPROVED** [review]

**Comment by sutaakar** [comment]
Race condition in BDD tests, will be addressed in separate PR.
/jenkins test

**Comment by sutaakar** [comment]
Failing due to `[ERROR] 'dependencies.dependency.version' for org.kie.kogito:process-management-addon:jar is missing`, I guess some changed artifacts are still to yet available in repository.

**Comment by sutaakar** [comment]
@cristianonicolai Can you please rebase? I thought that Jenkins will rebase as part of pipeline, but for some reason it doesn't look so, one of the failures is caused by something what was already fixed in recent commit.

**Comment by radtriste** [comment]
> Failing due to `[ERROR] 'dependencies.dependency.version' for org.kie.kogito:process-management-addon:jar is missing`, I guess some changed artifacts are still to yet available in repository.

I think it is because runtimes artifacts have been uploaded but examples nightly-master branch did not change yet due to problems

**Comment by sutaakar** [comment]
Looks like there was used an old image in the BDD tests, deleted the image tag manually and rerunning the test.
/jenkins test

**Comment by radtriste** [comment]
errors are unrelated to PR

**Comment by radtriste** [comment]
@cristianonicolai @ricardozanini I think it would make sense to cherry-pick to 1.8.x :)

**Pull request merged**
