### PR TITLE
KOGITO-6504 Update kogito-examples paths

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-6503

Due to https://github.com/kiegroup/kogito-examples/pull/1053

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by radtriste** [comment]
- `Deploy source files (dmn, drl, bpmn, bpmn2, ...) with CLI` tests will fail as long as Kogito 1.15 is not added to Quarkus platform 2.6 (see also Deploy source files (dmn, drl, bpmn, bpmn2, ...) with CLI)
Reviewing the others

**Comment by radtriste** [comment]
looks like there is an issue of communication between GH and Jenkins ...
https://jenkins-kogito-tools.kogito-cluster-0ad6762cc85bcef5745bb684498c2436-0000.us-south.containers.appdomain.cloud/job/kogito/job/kogito-operator-PR-check/542/#showFailuresLink shows only the source files errors. Means all ok. Gonna merge the PR

**Pull request merged**
