### PR TITLE
Cucumber tests: Fix WebHook mapping for both operators

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
@sutaakar 
```
Error: registry.stage.redhat.io/rhpam-7/rhpam-kogito-rhel8-operator:7.12.0: image not known
```
Maybe the name of the image built changed locally ? or there is an issue with the container engine ?
 looks like it cannot find the built image to push it to openshift registry

**Comment by sutaakar** [comment]
@radtriste The operator tag built is `registry.stage.redhat.io/rhpam-7/rhpam-kogito-rhel8-operator:7.13.0`. Seems like the pipeline resolves wrong operator tag.

**Comment by radtriste** [comment]
test failure due to quarkus platform 2.10 not yet released. PR can be merged

**Pull request merged**
