### PR TITLE
[KOGITO-5104] - [1.7.x] - RHPAM Kogito operator creates wrong default…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
… image tags

https://issues.redhat.com/browse/KOGITO-5104

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by spolti** [comment]
not sure it 1.7.x branch will be needed as well. I think only 1.5.x and master needs, @radtriste @AntStephenson, is that right?

**Comment by radtriste** [comment]
I think we don't need that here unless we absolutely want it in community release

**Review by ricardozanini — COMMENTED** [review]
I think it's a reasonable change, but only on master.

**Comment by spolti** [comment]
do we agree to close it without merge then?

**Comment by radtriste** [comment]
good for me

**Pull request closed without merging**
