### PR TITLE
[KOGITO-3792] Support Topic discovery on Kogito Apps

### PR DESCRIPTION
**Pull request by desmax74**
Signed-off-by: desmax74 <mdessi@redhat.com>
See: https://issues.redhat.com/browse/KOGITO-3792

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

### CODE REVIEW

**Comment by desmax74** [comment]
@vaibhavjainwiz @spolti

**Review by davidesalerno — APPROVED** [review]

**Comment by vaibhavjainwiz** [comment]
@desmax74 
In Jira comments it mentioned that `We need to also add the TopicDiscovery service to the Kogito Apps` which service does **Kogito Apps** refers?

**Comment by desmax74** [comment]
@vaibhavjainwiz was a comment of the 2020 from Ricardo, the topics discovery is here https://github.com/kiegroup/kogito-runtimes/blob/4533ab43cf517cc2480676deb3376f649cc8cb0d/addons/common/messaging/src/main/java/org/kie/kogito/addon/cloudevents/AbstractTopicDiscovery.java#L31 Implemented for Quarkus https://github.com/kiegroup/kogito-runtimes/blob/4533ab43cf517cc2480676deb3376f649cc8cb0d/quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/QuarkusTopicDiscovery.java#L33 and SpringBoot https://github.com/kiegroup/kogito-runtimes/blob/4533ab43cf517cc2480676deb3376f649cc8cb0d/springboot/addons/messaging/implementation/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringTopicDiscovery.java#L28

**Review by spolti — CHANGES_REQUESTED** [review]
One thing though, please update the RELEASE_NOTES.md.

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
@desmax74 can you please check the failing test?

**Review by ricardozanini — APPROVED** [review]

**Comment by desmax74** [comment]
@spolti 
` <testsuite name="Service Deployment: Prometheus" tests="1" skipped="0" failures="1" errors="0" time="555.314869555">
    <testcase name="Deploy dmn-drools-quarkus-metrics service and verify that it successfully connects to Prometheus" status="failed" time="555.314869555">
      <failure message="Step Prometheus instance is deployed, monitoring services with label name &#34;app&#34; and value &#34;dmn-drools-quarkus-metrics&#34;: Timeout waiting for 1 Pods with label name &#39;app&#39; and value &#39;prometheus&#39; available and running"></failure>`

**Comment by desmax74** [comment]
@spolti @radtriste is a infra problem let see this fake pr with just one word added on README, fail in the same way https://github.com/kiegroup/kogito-operator/pull/1209

**Pull request merged**
