### PR TITLE
[KOGITO-5390] Support using images without namespace part in KogitoRu…

### PR DESCRIPTION
**Pull request by sutaakar**
…ntime

https://issues.redhat.com/browse/KOGITO-5390

Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've ran `make before-pr` and everything is working accordingly
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by sutaakar** [comment]
Implemented by putting (optional) namespace as part of domain

**Comment by sutaakar** [comment]
Marking as WIP as BDD tests and CI needs to be adjusted too once the implementation is approved

**Review by vaibhavjainwiz — APPROVED** [review]
LGTM

**Comment by sutaakar** [comment]
Namespace is part of the domain now, we still need name separate in the same format as before as it is used for ImageStream naming.

**Comment by ricardozanini** [comment]
> Namespace is part of the domain now, we still need name separate in the same format as before as it is used for ImageStream naming.

That's what I meant. :sweat_smile:

**Review by spolti — APPROVED** [review]

**Pull request merged**
