### PR TITLE
Fix ANSIBLE_PULL_REPO path in run-olm-tests.sh

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
Many thanks for submitting your Pull Request :heart:! 

PR is raised to fix nightly build. Nightly build is failing due to incorrect OLM test path.
The default value of ANSIBLE_PULL_PATH is refered to old repo which is deprecated.
```
OP_TEST_ANSIBLE_PULL_REPO=${OP_TEST_ANSIBLE_PULL_REPO-"https://github.com/operator-framework/operator-test-playbooks"}
```
It should refer to `https://github.com/redhat-openshift-ecosystem/operator-test-playbooks`. 
To fix this issue we had overide its default value
```
export OP_TEST_ANSIBLE_PULL_REPO=https://github.com/redhat-openshift-ecosystem/operator-test-playbooks
```

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Review by radtriste — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by radtriste** [comment]
not sure what is wrong but OLM tests are failing on another part ...

**Comment by vaibhavjainwiz** [comment]
I raised an issue on `operator-test-playbook` repo to understand it.
https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/issues/305

**Comment by spolti** [comment]
hi @vaibhavjainwiz, what is the status of this PR?

**Comment by vaibhavjainwiz** [comment]
After fixing path issue we are facing blow issues in OLM check.
```
The conditional check 'cluster_type == "ocp"' failed. The error was: error while evaluating conditional (cluster_type == "ocp"): 'cluster_type' is undefined
  
    The error appears to be in '/playbooks/upstream/roles/operator_info/tasks/op_info_ver.yml': line 157, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
```

I create an issue on operator-test-playbook repo to understand it better. Just waiting for their reply

**Comment by spolti** [comment]
closed in favor of https://github.com/kiegroup/kogito-operator/pull/1135/

**Pull request closed without merging**
