### PR TITLE
Updating references to the new kie-ci actions folder.

### PR DESCRIPTION
**Pull request by bacciotti**

### CODE REVIEW

**Review by lampajr — APPROVED** [review]

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by spolti** [comment]
does it needs to be cherry-picked to 1.13.x-next and 1.13.x-blue-next branches?

**Comment by bacciotti** [comment]
@spolti yes, I guess it does.

**Comment by spolti** [comment]
oh, it is backport.

**Comment by bacciotti** [comment]
@spolti done.

**Pull request merged**
