### PR TITLE
Various BDD adjustments

### PR DESCRIPTION
**Pull request by sutaakar**
Many thanks for submitting your Pull Request :heart:! 

Adjustments separated into commits.
All are related to the support of BDD tests for Kubernetes environment.
More will come!
I didn't create a JIRA for this as the adjustments are not significant and are focusing just on tests.

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by radtriste — APPROVED** [review]
lgtm

**Comment by sutaakar** [comment]
Rebased
/jenkins test

**Comment by sutaakar** [comment]
Marshalling error?
/jenkins test

**Review by MarianMacik — APPROVED** [review]

**Pull request merged**
