### PR TITLE
KOGITO-6294 : ProtoBuf ConfigMap should be created on instantiation o…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
…f KogitoRuntime

Jira issue : https://issues.redhat.com/browse/KOGITO-6294

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've ran `make before-pr` and everything is working accordingly
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run operator BDD testing</b>
  Please add comment: <b>/jenkins test</b>

* <b>Run RHPAM operator BDD testing</b>
  Please add comment: <b>/jenkins RHPAM test</b>
</details>

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
@vaibhavjainwiz does this one depends on the friendly-user changes?

**Review by sutaakar — APPROVED** [review]

**Comment by sutaakar** [comment]
Issues with connection to the cloud instance.
/jenkins test

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
`Deploy source files in folder with CLI` failure is expected as `nightly-main` branch has not been updated due to https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/.5Bmain.5D.20kogito-examples.20failing.20on.20Outbox.20IT

retesting the `Install Kogito Data Index with Infinispan` as it seems there was an infra problem ...

/jenkins test

**Comment by radtriste** [comment]
last failing scenarios are failing due to infra instabilities.
`Install Kogito Data Index with Infinispan` is successful in that run.

PR can be safely merged

**Pull request merged**
