### PR TITLE
Upgrade Kogito Operator tested integrations

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've ran `make before-pr` and everything is working accordingly
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Is this matrix on our docs as well? cc @hmanwani-rh

**Comment by hmanwani-rh** [comment]
> Is this matrix on our docs as well? cc @hmanwani-rh

@ricardozanini no, it is not available in the Kogito docs.

**Review by radtriste — APPROVED** [review]

**Comment by ricardozanini** [comment]
> > Is this matrix on our docs as well? cc @hmanwani-rh
> 
> @ricardozanini no, it is not available in the Kogito docs.

@sutaakar, IIRC we talked about having this matrix on docs as well? I don't remember :(

**Review by spolti — APPROVED** [review]

**Comment by sutaakar** [comment]
@ricardozanini I think so though I don't remember either. Question is how to sync it between places.

**Comment by radtriste** [comment]
we could have a link into the doc which points to released tags README.md section or ?

**Comment by ricardozanini** [comment]
> we could have a link into the doc which points to released tags README.md section or ?

+1, yeah we can keep this one updated and have the links in the doc. @briandooley @hmanwani-rh what do you guys think about this approach?

**Comment by hmanwani-rh** [comment]
> > we could have a link into the doc which points to released tags README.md section or ?
> 
> +1, yeah we can keep this one updated and have the links in the doc. @briandooley @hmanwani-rh what do you guys think about this approach?

@ricardozanini sure, we can do that.
@sutaakar is it okay if you create the related docs PR or do you want us to create one?

**Comment by radtriste** [comment]
Created https://issues.redhat.com/browse/BXMSDOC-8098 and assigned to Karel

**Pull request merged**
