### PR TITLE
[KOGITO-5573] Kogito Operator Data-Index Unable to connect to Infinis…

### PR DESCRIPTION
**Pull request by sutaakar**
…pan Instance

https://issues.redhat.com/browse/KOGITO-5573

Signed-off-by: Karel Suta <ksuta@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've ran `make before-pr` and everything is working accordingly
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](https://github.com/kiegroup/kogito-operator/blob/main/RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by sutaakar** [comment]
@radtriste Should I cherrypick this also to 1.9.x branch?

**Review by radtriste — APPROVED** [review]
lgtm

**Comment by radtriste** [comment]
> @radtriste Should I cherrypick this also to 1.9.x branch?

yes please :)

**Review by Kevin-Mok — APPROVED** [review]

**Review by spolti — APPROVED** [review]
@sutaakar many thanks for handling this issue!

**Comment by spolti** [comment]
@vaibhavjainwiz would you like to take a look before we merge it?

**Review by ricardozanini — APPROVED** [review]
Many thanks for taking care of this important issue, @sutaakar

**Review by vaibhavjainwiz — APPROVED** [review]

**Pull request merged**
