### PR TITLE
[1.5.x] [KOGITO-4974] Corrected OLM tests on release branch

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-4974

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
https://github.com/kiegroup/kogito-operator/pull/853/files created to update automatically as part of the pipeline

**Review by ricardozanini — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
PR checks working. Testing quickly the deploy pipeline.

**Comment by radtriste** [comment]
I could not use `1.5.0-snapshot` back as it was creating problems with the OLM testing, so I went for the next micro ...
I guess now we don't have to store on repo all the different csv, this is no problem to update to next micro after a release.
https://github.com/kiegroup/kogito-operator/pull/853 will reflect that change and add a `set next snapshot` stage which update to next micro version

**Comment by radtriste** [comment]
deploy test are all good

**Pull request merged**
