### PR TITLE
[KOGITO-8495] Bump quarkus version to 2.16.0.Final

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-8495

Please review and merge
- https://github.com/kiegroup/kogito-pipelines/pull/769
- https://github.com/kiegroup/kogito-docs/pull/279
- https://github.com/kiegroup/kogito-images/pull/1403
- https://github.com/kiegroup/kogito-runtimes/pull/2734
- https://github.com/kiegroup/drools/pull/4910
- https://github.com/kiegroup/kogito-examples/pull/1534
- https://github.com/kiegroup/kogito-apps/pull/1589
- https://github.com/kiegroup/kogito-operator/pull/1349

### CODE REVIEW

**Comment by radtriste** [comment]
depends on https://github.com/kiegroup/kogito-images/pull/1403

**Review by spolti — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
